/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelrodrigues;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author danil
 */
public class Clientes2 extends javax.swing.JFrame {

   
    public Clientes2() throws IOException {
        initComponents();
        
         setLocationRelativeTo(null);
         Principal form = new Principal();
         
         FileReader ArquivoDeLeitura = new FileReader(form.arquivo5);
         BufferedReader Leitor = new BufferedReader(ArquivoDeLeitura);
 while (Leitor.ready()) {
 String linha = Leitor.readLine();
 txtQuarto1.append(linha+"\n");
 }
Leitor.close();
ArquivoDeLeitura.close(); 
 FileReader ArquivoDeLeitura2 = new FileReader(form.arquivo6);
  BufferedReader Leitor2 = new BufferedReader(ArquivoDeLeitura2);
 while (Leitor2.ready()) {
 String linha = Leitor2.readLine();
 txtQuarto2.append(linha+"\n");
 }
Leitor.close();
ArquivoDeLeitura.close(); 

 FileReader ArquivoDeLeitura3 = new FileReader(form.arquivo7);
  BufferedReader Leitor3 = new BufferedReader(ArquivoDeLeitura3);
 while (Leitor3.ready()) {
 String linha = Leitor3.readLine();
 txtQuarto3.append(linha+"\n");
 }
Leitor.close();
ArquivoDeLeitura.close(); 

 FileReader ArquivoDeLeitura4 = new FileReader(form.arquivo8);
  BufferedReader Leitor4 = new BufferedReader(ArquivoDeLeitura4);
 while (Leitor4.ready()) {
 String linha = Leitor4.readLine();
 txtQuarto4.append(linha+"\n");
 }
Leitor.close();
ArquivoDeLeitura.close(); 



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txQuart3 = new javax.swing.JScrollPane();
        txtQuarto4 = new javax.swing.JTextArea();
        txQuart2 = new javax.swing.JScrollPane();
        txtQuarto3 = new javax.swing.JTextArea();
        txQuart1 = new javax.swing.JScrollPane();
        txtQuarto2 = new javax.swing.JTextArea();
        txQuart = new javax.swing.JScrollPane();
        txtQuarto1 = new javax.swing.JTextArea();
        btCADCAN = new javax.swing.JButton();
        brVoltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        txQuart3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 51, 0)));
        txQuart3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        txQuart3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtQuarto4.setEditable(false);
        txtQuarto4.setColumns(20);
        txtQuarto4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txtQuarto4.setRows(5);
        txQuart3.setViewportView(txtQuarto4);

        getContentPane().add(txQuart3);
        txQuart3.setBounds(900, 230, 240, 330);

        txQuart2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 51, 0)));
        txQuart2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        txQuart2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtQuarto3.setEditable(false);
        txtQuarto3.setColumns(20);
        txtQuarto3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txtQuarto3.setRows(5);
        txQuart2.setViewportView(txtQuarto3);

        getContentPane().add(txQuart2);
        txQuart2.setBounds(614, 230, 240, 330);

        txQuart1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 51, 0)));
        txQuart1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        txQuart1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtQuarto2.setEditable(false);
        txtQuarto2.setColumns(20);
        txtQuarto2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txtQuarto2.setRows(5);
        txQuart1.setViewportView(txtQuarto2);

        getContentPane().add(txQuart1);
        txQuart1.setBounds(330, 230, 240, 330);

        txQuart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 51, 0)));
        txQuart.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        txQuart.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtQuarto1.setEditable(false);
        txtQuarto1.setColumns(20);
        txtQuarto1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txtQuarto1.setRows(5);
        txQuart.setViewportView(txtQuarto1);

        getContentPane().add(txQuart);
        txQuart.setBounds(40, 230, 240, 330);

        btCADCAN.setBackground(new java.awt.Color(251, 51, 0));
        btCADCAN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btCADCAN.setForeground(new java.awt.Color(255, 255, 255));
        btCADCAN.setText("RESERVAR/CANCELAR");
        btCADCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCADCANActionPerformed(evt);
            }
        });
        getContentPane().add(btCADCAN);
        btCADCAN.setBounds(611, 590, 155, 40);

        brVoltar.setBackground(new java.awt.Color(251, 51, 0));
        brVoltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        brVoltar.setForeground(new java.awt.Color(255, 255, 255));
        brVoltar.setText("PÁGINA ANTERIOR");
        brVoltar.setActionCommand("Voltar");
        brVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(brVoltar);
        brVoltar.setBounds(415, 590, 155, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QUARTO 8");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(990, 200, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QUARTO 7");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(700, 200, 80, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUARTO 6");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 200, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUARTO 5");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 200, 80, 20);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelrodrigues/BackgroundHotel.png"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(1202, 760));
        lblBackground.setMinimumSize(new java.awt.Dimension(1202, 760));
        lblBackground.setPreferredSize(new java.awt.Dimension(1202, 760));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1200, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCADCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCADCANActionPerformed
       Principal form = new Principal();
       form.setVisible(true);
       dispose();
    }//GEN-LAST:event_btCADCANActionPerformed

    private void brVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brVoltarActionPerformed
        try {
            Clientes form2 = new Clientes();
            form2.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Clientes2().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Clientes2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brVoltar;
    private javax.swing.JButton btCADCAN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JScrollPane txQuart;
    private javax.swing.JScrollPane txQuart1;
    private javax.swing.JScrollPane txQuart2;
    private javax.swing.JScrollPane txQuart3;
    private javax.swing.JTextArea txtQuarto1;
    private javax.swing.JTextArea txtQuarto2;
    private javax.swing.JTextArea txtQuarto3;
    private javax.swing.JTextArea txtQuarto4;
    // End of variables declaration//GEN-END:variables

}
