/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelrodrigues;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author danil
 */
public class Pagina2 extends javax.swing.JFrame {

    /**
     * Creates new form Pagina2
     */
    public Pagina2() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btInicio = new javax.swing.JButton();
        btVerCliente = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(417, 619));
        setMinimumSize(new java.awt.Dimension(417, 619));
        setPreferredSize(new java.awt.Dimension(417, 619));
        setResizable(false);
        setSize(new java.awt.Dimension(417, 619));
        getContentPane().setLayout(null);

        btInicio.setBackground(new java.awt.Color(251, 51, 0));
        btInicio.setForeground(new java.awt.Color(255, 255, 255));
        btInicio.setText("RESERVA/CANCELAR");
        btInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btInicio);
        btInicio.setBounds(30, 510, 155, 40);

        btVerCliente.setBackground(new java.awt.Color(251, 51, 0));
        btVerCliente.setForeground(new java.awt.Color(255, 255, 255));
        btVerCliente.setText("VER RESERVAS");
        btVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btVerCliente);
        btVerCliente.setBounds(220, 510, 155, 40);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelrodrigues/pagina3.png"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(400, 600));
        lblBackground.setMinimumSize(new java.awt.Dimension(400, 600));
        lblBackground.setPreferredSize(new java.awt.Dimension(400, 600));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 400, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerClienteActionPerformed
        try {
            Clientes form2 = new Clientes();
            form2.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    
                            
    }//GEN-LAST:event_btVerClienteActionPerformed

    private void btInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioActionPerformed
Principal form = new Principal();
form.setVisible(true);
dispose();
    }//GEN-LAST:event_btInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagina2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInicio;
    private javax.swing.JButton btVerCliente;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
